### ISSUE TITLE
Japanese Nuget package name is incorrect

### ISSUE THREAD

**Issue by shunsuke-kawai** [MicrosoftDocs/xamarin-docs.ja-jp#128]
Japanese
&gt;パッケージ名に関係なく、pcl-sqlite-net NuGet パッケージを .NET Standard プロジェクトでも使用します。
English
&gt;Despite the package name, use the sqlite-net-pcl NuGet package even in .NET Standard projects.

Package name is not "pcl-sqlite-net", it is "sqlite-net-pcl" correctly.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 3ab6098a-39c7-151f-124b-f88aa62c4659
* Version Independent ID: dc27c1e4-ff12-c1af-646a-c2617def0bcd
* Content: [Xamarin.Forms のローカル データベース - Xamarin](https://docs.microsoft.com/ja-jp/xamarin/xamarin-forms/app-fundamentals/databases#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/databases.md](https://github.com/MicrosoftDocs/xamarin-docs.ja-JP/blob/live/docs/xamarin-forms/app-fundamentals/databases.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by CeciAc** [comment]
Hello, @shunsuke-kawai 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@shunsuke-kawai

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/xamarin/xamarin-forms/app-fundamentals/databases#feedback

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
