### ISSUE TITLE
In Japanese page, "Objective Sharpie" is translated to "目標油性"

### ISSUE THREAD

**Issue by anatawa12** [MicrosoftDocs/xamarin-docs.ja-jp#156]
In Japanese page, "Objective Sharpie" is translated to "目標油性". 
"Objective Sharpie" is a proper noun so I highly recommend you not to translate "Objective Sharpie" like "C#".

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: f07fe4d8-4ec3-7dda-0583-266c4b0ce065
* Version Independent ID: 189d3f24-8911-aaf5-fef5-174e7ab9b332
* Content: [目標油性とバインディングの作成 - Xamarin](https://docs.microsoft.com/ja-jp/xamarin/cross-platform/macios/binding/objective-sharpie/index#feedback)
* Content Source: [docs/cross-platform/macios/binding/objective-sharpie/index.md](https://github.com/MicrosoftDocs/xamarin-docs.ja-JP/blob/live/docs/cross-platform/macios/binding/objective-sharpie/index.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by CeciAc** [comment]
Hello, @anatawa12 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@anatawa12

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/xamarin/cross-platform/macios/binding/objective-sharpie/index#feedback

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team

**Comment by anatawa12** [comment]
@CeciAc 
Sorry to late check this issue. I checked that "Objective Sharpie" is not translated to "目標油性" in https://docs.microsoft.com/ja-jp/xamarin/cross-platform/macios/binding/objective-sharpie/index. But some "Objective Sharpie" has been translated to "油性の目標" and in other pages, "Objective Sharpie" has been translated to "目標油性". Could you disable translation for "Objective Sharpie"? 
And please repoen this issue
