### ISSUE TITLE
Xenarin が Jenkins をサポートしていないのはなぜですか

### ISSUE THREAD

**Issue by kuramochia** [MicrosoftDocs/xamarin-docs.ja-jp#260]
typo と思われます。
× Xenarin → 〇Xamarin

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: d1ebada8-d5b7-49c1-f546-3ed250296782
* Version Independent ID: 341b5539-ced9-e4b5-ee74-23ca77f3767c
* Content: [一般的によく寄せられる質問 - Xamarin](https://docs.microsoft.com/ja-jp/xamarin/cross-platform/troubleshooting/questions/index#feedback)
* Content Source: [docs/cross-platform/troubleshooting/questions/index.md](https://github.com/MicrosoftDocs/xamarin-docs.ja-jp/blob/live/docs/cross-platform/troubleshooting/questions/index.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by srvbpigh** [comment]
Hello, @kuramochia
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@kuramochia

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/xamarin/cross-platform/troubleshooting/questions/index

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
