### ISSUE TITLE
本ページは Human translation して欲しい

### ISSUE THREAD

**Issue by TomohiroSuzuki128** [MicrosoftDocs/xamarin-docs.ja-jp#314]
本ページは Xamarin.iOS の重要な仕組みついての解説でほかにこの情報があるページは無いので、ぜひ 
 Human translation していただきたいです。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 9ac6ba10-353a-e249-ced4-f5ef039d3fed
* Version Independent ID: 1dec19b4-ad2f-9942-d5f1-67020004e2c3
* Content: [Xamarin. iOS API の設計 - Xamarin](https://docs.microsoft.com/ja-jp/xamarin/ios/internals/api-design/index)
* Content Source: [docs/ios/internals/api-design/index.md](https://github.com/MicrosoftDocs/xamarin-docs.ja-jp/blob/live/docs/ios/internals/api-design/index.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by srvbpigh** [comment]
Hello, @TomohiroSuzuki128
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@TomohiroSuzuki128
 フィードバックをお送りいただきありがとうございました。問題のページは機械翻訳されており、常に完全に理解可能であるとは限りません。最近、右側に "英語で読む" オプションが追加されました。このオプションを使用すると、言語設定を変更しなくても英語バージョンに切り替えることができます。 
 敬具 
Microsoft DOCS International Team

@JasonCard

**Comment by JasonCard** [comment]
@TomohiroSuzuki128 貴重なフィードバックをありがとうございます。本ページおよび関連しているページのHuman Translationを検討いたします。今後ともどうぞよろしくお願いします。

@CeciAc Thank you for @ mentioning me. I do value this kind of feedback, so please continue to do so in the future.

**Comment by TomohiroSuzuki128** [comment]
Thanks for the human translation of this page!

**Comment by JasonCard** [comment]
@TomohiroSuzuki128 You're welcome and thank you again for your valuable feedback.
