### ISSUE TITLE
SKBitmap.Encode() is obsolate.

### ISSUE THREAD

**Issue by H-J-Ainashi** [MicrosoftDocs/xamarin-docs.ja-jp#370]
SKBitmap.Encode() is obsolate, so, we should use SKPixmap.Encode().

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 1b7a97e7-31c4-f35b-a3ad-1231df7a0e06
* Version Independent ID: 23c889c4-e3d3-f22e-33c9-9212f8d7d66e
* Content: [SkiaSharp のビットマップをファイルに保存します。 - Xamarin](https://docs.microsoft.com/ja-jp/xamarin/xamarin-forms/user-interface/graphics/skiasharp/bitmaps/saving#feedback)
* Content Source: [docs/xamarin-forms/user-interface/graphics/skiasharp/bitmaps/saving.md](https://github.com/MicrosoftDocs/xamarin-docs.ja-jp/blob/live/docs/xamarin-forms/user-interface/graphics/skiasharp/bitmaps/saving.md)
* Product: **xamarin**
* Technology: **xamarin-skiasharp**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by srvbpigh** [comment]
Hello, @H-J-Ainashi
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
こんにちは、@H-J-Ainashi  

 フィードバックをお送りいただきありがとうございました。問題のページは機械翻訳されており、常に完全に理解可能であるとは限りません。最近、右側に "英語で読む" オプションが追加されました。このオプションを使用すると、言語設定を変更しなくても英語バージョンに切り替えることができます。  

 敬具  

Microsoft DOCS International Team
