### ISSUE TITLE
誤訳があります

### ISSUE THREAD

**Issue by masatoru** [MicrosoftDocs/xamarin-docs.ja-jp#427]
焼討 Base→Firebase

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 92f390d9-cbd0-ab8c-6c8c-49df76d1b8e0
* Version Independent ID: 15739c2f-afbb-c21d-b96f-fabe7060e410
* Content: [Azure Notification Hubs と Xamarin. Forms を使用してプッシュ通知を送信および受信する - Xamarin](https://docs.microsoft.com/ja-jp/xamarin/xamarin-forms/data-cloud/azure-services/azure-notification-hub#feedback)
* Content Source: [docs/xamarin-forms/data-cloud/azure-services/azure-notification-hub.md](https://github.com/MicrosoftDocs/xamarin-docs.ja-jp/blob/live/docs/xamarin-forms/data-cloud/azure-services/azure-notification-hub.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by srvbpigh** [comment]
Hello, @masatoru
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@masatoru  様:  

投稿いただき、ありがとうございます。 

現在、機械翻訳されたコンテンツに対する翻訳の問題へのコントリビューションはできません。 

人間が翻訳したコンテンツに関するフィードバックやご意見をお寄せください。人間が翻訳したコンテンツは機械翻訳エンジンをトレーニングするために使用されているため、お客様は、時間が経つにつれ人間および機械の両方による翻訳の質を向上させることに貢献できます。 

人間が翻訳したトピックは、各コンテンツ ファイルのヘッダーの translationtype メタデータ値 "HT" (機械翻訳の場合は "MT") によって、機械翻訳されたトピックと区別できます。 


サポートいただきありがとうございます。 

Microsoft DOCS グローバル エクスペリエンス チーム

**Comment by JasonCard** [comment]
Hi @masatoru 

Thank you for your valuable feedback.
We are currently working to fix this over-localization issue.

Best regards,
Jason

**Comment by JasonCard** [comment]
Hi @masatoru 

Thank you again for your feedback.
I've confirmed this issue is now resolved.

Best regards,
Jason
