### ISSUE TITLE
Proposal for Japanese translation correction of CheckBox visual states

### ISSUE THREAD

**Issue by YabukiMunehisa** [MicrosoftDocs/xamarin-docs.ja-jp#431]
site language en-us
CheckBox has an IsChecked VisualState that can be used to initiate a visual change to the CheckBox when it becomes checked.
The following XAML example shows how to define a visual state for the IsChecked state:

site language ja-jp
CheckBoxには、が IsChecked VisualState チェックされたときに、へのビジュアル変更を開始するために使用できるがあり CheckBox ます。
次の XAML の例は、状態の表示状態を定義する方法を示してい IsChecked ます。

[フィードバックをこちらに入力してください]
CheckBox には、IsChecked プロパティがあります。 CheckBox がチェック状態になったときの視覚的な変更に VisualState を使用することができます。
次の XAML の例は、IsChecked プロパティの状態で VisualState を定義する方法を示しています。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: b58c2dc4-4072-c681-f047-c11e26ddf7f1
* Version Independent ID: f94ad816-056f-c661-94ec-0eda4325d802
* Content: [Xamarin.FormsCheckBox - Xamarin](https://docs.microsoft.com/ja-jp/xamarin/xamarin-forms/user-interface/checkbox)
* Content Source: [docs/xamarin-forms/user-interface/checkbox.md](https://github.com/MicrosoftDocs/xamarin-docs.ja-jp/blob/live/docs/xamarin-forms/user-interface/checkbox.md)
* Product: ****
* Technology: ****
* GitHub Login: @olprod
* Microsoft Alias: ****

**Comment by srvbpigh** [comment]
Hello, @YabukiMunehisa
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello @YabukiMunehisa 

Thank you for your contribution.

Contributions on translation problems against machine-translated content are currently not accepted.

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations.

Human translated topics can be distinguished from machine translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file.

Many thanks for your support.

Microsoft DOCS Global Experience Team
