### ISSUE TITLE
AOTコンパイル , LLVM 最適化コンパイラ の有効化 のオプションに関しまして

### ISSUE THREAD

**Issue by tknr** [MicrosoftDocs/xamarin-docs.ja-jp#45]
お世話になります。
弊社では Visual Studio Professionalライセンスを所有しておりますが、
AOTコンパイル
LLVM 最適化コンパイラ
について、Professionalライセンス での使用は可能でしょうか?
お手数ですがご返信のほどお願い致します。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: f43472af-a9d3-8bef-0f24-b81f8f6cd2dd
* Version Independent ID: 42cfbea5-0b4c-a0a3-4cce-1edf5523f605
* Content: [リリースに向けてアプリケーションを準備する - Xamarin](https://docs.microsoft.com/ja-jp/xamarin/android/deploy-test/release-prep/?tabs=vswin)
* Content Source: [docs/android/deploy-test/release-prep/index.md](https://github.com/MicrosoftDocs/xamarin-docs.ja-JP/blob/live/docs/android/deploy-test/release-prep/index.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by LisandroSu** [comment]
こんにちは、@tknr 

ご協力に深く感謝いたします。Microsoft の担当チームでは、ドキュメントに関するフィードバックに対してのみお答えすることができます。 

ドキュメント ページの下部にある [製品のフィードバックを送信] ボタンを使用して、製品に関するフィードバックをログに記録してください。 

ドキュメントに関するフィードバックがある場合は、このチャンネルをご自由に使用して、内容をログに記録してください。 

記事の品質向上にご協力いただき誠にありがとうございました。  

敬具 
Microsoft DOCS International Team
