### ISSUE TITLE
Translation of DateTime page in Japanese

### ISSUE THREAD

**Issue by chooyan-eng** [MicrosoftDocs/xamarin-docs.ja-jp#67]
The paragraph below

"The platforms implement this date picker in very different ways, but each approach is familiar to users of that platform:"

is now translated into Japanese like 

"プラットフォームは、非常にさまざまな方法でこの日付の選択を実装しますが、そのプラットフォームのユーザーにとって馴染み深い。"

However, I suggest alternative translation below,

"各プラットフォームは非常にさまざまな方法でこの日付の選択を実装していますが、これらはそのプラットフォームのユーザーにとって馴染み深いアプローチです。"

The points are below.

- the sentence stops with adjective "馴染み深い" and seems halfway as a sentence of this kind of document. 
- "プラットフォームは" sounds "a platform" (not "platforms"), so the letter "各" that means "multiple" should be added.

Thanks.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: fc655d93-15fe-2b1e-83c1-e1ee53f8336b
* Version Independent ID: b58f69b0-d871-4efb-8862-9df8dd34d588
* Content: [Xamarin.Forms DatePicker - Xamarin](https://docs.microsoft.com/ja-jp/xamarin/xamarin-forms/user-interface/datepicker)
* Content Source: [docs/xamarin-forms/user-interface/datepicker.md](https://github.com/MicrosoftDocs/xamarin-docs.ja-JP/blob/live/docs/xamarin-forms/user-interface/datepicker.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by CeciAc** [comment]
Hello, @chooyan-eng 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @chooyan-eng 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/xamarin/xamarin-forms/user-interface/datepicker. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team

**Comment by chooyan-eng** [comment]
Hello, @CeciAc 

Thank you for accepting my translation. 
I'm really glad that I could contribute to your articles.

Thanks.
Tsuyoshi Chujo @chooyan-eng
